export const SET_INGRIDENTS = 'SET_INGRIDENTS';
export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const SET_INGRIDENTS_PRICES = 'SET_INGRIDENTS_PRICES';
export const SET_TOTAL_PRICE = 'SET_TOTAL_PRICE';
export const ERROR = 'ERROR';


