export const SET_INGRIDENTS = 'SET_INGRIDENTS';
export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const SET_INGRIDENTS_PRICES = 'SET_INGRIDENTS_PRICES';
export const ADD_TOTAL = 'ADD_TOTAL';
export const SUB_TOTAL = 'SUB_TOTAL';
export const ERROR = 'ERROR';


